# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Ruyi Zha"
description              : ""
repository               : "Ruyi-Zha/Ruyi-Zha.github.io"
google_scholar_stats_use_cdn : true

# google analytics
google_analytics_id      :  # get google_analytics_id from https://analytics.google.com/analytics/

# SEO Related
google_site_verification :  # get google_site_verification from https://search.google.com/search-console/about
bing_site_verification   :  # get bing_site_verification from https://www.bing.com/webmasters/about
baidu_site_verification  :  # get baidu_site_verification from https://ziyuan.baidu.com/login/index?u=/site/index

# Site Author
author:
  name             : "Ruyi Zha"
  avatar           : "images/potrait.jpg"
  bio              : "Researcher in 3D vision"
  location         : "Melbourne, Australia"
  employer         : "Monash University"
  pubmed           : 
  googlescholar    : "https://scholar.google.com/citations?user=_5W6W7oAAAAJ&hl=en"
  email            : "ruyi.zha@monash.edu"
  researchgate     : "https://www.researchgate.net/profile/Ruyi-Zha?ev=hdr_xprf" # e.g., "https://www.researchgate.net/profile/yourprofile"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "Ruyi-Zha" # e.g., "github username"
  google_plus      :
  keybase          :
  instagram        : "ruyi_anu"
  impactstory      : # e.g., "https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         : "ruyi-zha-208a17223" # e.g., "linkedin username"
  dblp             : "https://dblp.org/pid/280/0677.html" # e.g., "https://dblp.org/pid/xx/xxxx.html"
  orcid            : "https://orcid.org/0009-0005-0410-1807" # e.g., "https://orcid.org/xxxx"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  rednote          : https://www.xiaohongshu.com/user/profile/5ae538b7e8ac2b7d44598e47 # e.g., "https://www.xiaohongshu.com/user/profile/xxxxxxxx"
  xing             :
  youtube          :
  wikipedia        :


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Australia/Sydney # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
